// 视图type
export default {
  text: 'InputModule',
  textarea: 'TextareaModule',
  'number-input': 'NumberInputModule',
  radio: 'RadioModule',
  checkbox: 'CheckboxModule',
  'binary-choice': 'BinaryChoiceModule',
  select: 'SelectModule',
  'radio-star': 'StarModule',
  'radio-nps': 'NpsModule',
  city: 'CityModule',
  vote: 'VoteModule',
  'matrix-checkbox': 'GroupModule',
  selectMoreModule: 'SelectMoreModule',
  cascader: 'CascaderModule',
  datetime: 'DateTimeModule',
  'matrix-choice': 'MatrixChoiceModule',
  'matrix-scale': 'MatrixScaleModule',
  ranking: 'RankingModule',
  'matrix-nps': 'MatrixNpsModule',
  'matrix-input': 'MatrixInputModule',
  'matrix-textarea': 'MatrixTextareaModule',
  'file-upload': 'FileUploadModule',
  'image-upload': 'ImageUploadModule'
}
